const DISPLAY_LABELS: Record<string, string> = {
  PENDING: '대기 중',
  PROCESSING: '처리 중',
  READY: '준비 완료',
  FAILED: '처리 실패',
  ACTIVE: '활성',
  INACTIVE: '비활성',
  IN_USE: '사용 중',
  DRAFT: '초안',
  NOT_STARTED: '시작 전',
  IN_PROGRESS: '진행 중',
  COMPLETED: '완료',
  DONE: '완료',
  SKIPPED: '건너뜀',
  DISMISSED: '제외',
  RESTRICTED: '역할별 공개',
  PERSON: '담당자 미팅',
  ON_TRACK: '정상 진행',
  AT_RISK: '지연 위험',
  AHEAD: '앞서 진행',
  NO_PLAN: '계획 미생성',
  DISABLED: '비활성',
  INVITED: '초대됨',
  ACCEPTED: '수락됨',
  EXPIRED: '만료됨',
  REVOKED: '철회됨',
  SUCCESS: '성공',
  FAILURE: '실패',
  DENIED: '거부',
  HIGH: '높음',
  MEDIUM: '보통',
  LOW: '낮음',
  NEW_HIRE: '신입 구성원',
  MEMBER: '구성원',
  MANAGER: '관리 담당자',
  ADMIN: '관리자',
  OWNER: '소유자',
  WORKSPACE: '워크스페이스 전체',
  ROLE_BASED: '역할별 공개',
  PRIVATE: '비공개',
  DOC_VIEW: '문서 조회',
  DOC_ACCESS_DENIED: '문서 접근 거부',
  CHAT_QUERY: 'AI 질문',
  PLAN_REGENERATE: '계획 재생성',
  MEMBER_INVITE: '구성원 초대',
  VIEW: '조회',
  DOWNLOAD: '다운로드',
  QUERY: '질문',
  DOCUMENT: '문서',
  CHECKLIST: '체크리스트',
  PRACTICE: '실습',
  PLAN: '계획',
  PDF: 'PDF 문서',
  XLSX: '엑셀 문서',
  DOCX: '워드 문서',
  PPTX: '프레젠테이션',
  CSV: '표 형식 파일',
  JSON: '데이터 파일',
  TXT: '텍스트 문서',
  EXCEL: '엑셀 문서',
};

export function getDisplayLabel(value?: string | null): string {
  if (!value) return '—';
  return DISPLAY_LABELS[value.toUpperCase()] ?? value;
}

export function getDisplayLabels(values?: string[] | null): string {
  if (!values?.length) return '—';
  return values.map(getDisplayLabel).join(', ');
}
